### ISSUE TITLE
Transforms on files in subdirectories aren't supported

### ISSUE THREAD

**Issue by marcbachmann** [boennemann/github-change-remote-file#6]
I've tried to fix that in here: https://github.com/marcbachmann/github-change-remote-file/commit/921a97f8ad2eab826803ab7895f8622fdd8f6236
But then I saw that github probably needs an update of a whole tree and currently reading of a file and updating a tree are completely separated.

**Comment by finnp** [comment]
Shouldn't updating just be a call to: https://developer.github.com/v3/repos/contents/#update-a-file

**Comment by marcbachmann** [comment]
That would create the branch at the time the file gets pushed and not when the pull request gets created.
And that endpoint also only allows one file change per commit. But that's what this module is currently doing anyways.

**Comment by christophwitzko** [comment]
This feature is now included in `github-change-remote-file@4.1.0`.
